### ISSUE TITLE
Import symbol set from CMUdict

### ISSUE THREAD

**Issue by dzucconi** [dzucconi/corrasable#10]
https://github.com/cmusphinx/cmudict/blob/master/cmudict.vp

**Comment by jonaslund** [comment]
Thanks. Makes it clear! Do you have approx stats on the server footprint and usage?

**Comment by dzucconi** [comment]
@jonaslund it's a pretty standard Rails app. I've been running it on a single Heroku Hobby dyno which has 512MB of RAM without issue and it rarely breaches 256MB. Admittedly it doesn't get a ton of traffic, so YMMV.
